// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type {
	StoryblokRichtext,
	StoryblokMultilink,
	StoryblokAsset,
} from "../storyblok.d.ts";
export interface Blog {
	title?: string;
	description?: StoryblokRichtext;
	component: "blog";
	_uid: string;
	[k: string]: unknown;
}

export interface Feature {
	name?: string;
	component: "feature";
	_uid: string;
	[k: string]: unknown;
}

export interface FooterItem {
	items?: Links[];
	component: "footer_item";
	_uid: string;
	[k: string]: unknown;
}

export interface Global {
	burger_menu?: Menu[];
	footer?: FooterItem[];
	component: "global";
	_uid: string;
	[k: string]: unknown;
}

export interface Grid {
	columns?: (
		| Blog
		| Feature
		| FooterItem
		| Global
		| Grid
		| heroSection
		| heroVideoSection
		| Item
		| Links
		| Menu
		| MenuItem
		| Page
		| Robots
		| leftImageSection
		| rightImageSection
		| SubMenu
		| Teaser
	)[];
	component: "grid";
	_uid: string;
	[k: string]: unknown;
}

export interface heroSection {
	//add button and image here
	bg_image?: StoryblokAsset;
	title?: string;
	description?: StoryblokRichtext;
	component: "hero_section";
	_uid: string;
	[k: string]: unknown;
}
export interface heroVideoSection {
  video_thumb?: StoryblokAsset;
  video?: StoryblokAsset;
  title?: StoryblokRichtext;
  description?: StoryblokRichtext;
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  link_text?: string;
  component: "hero_video_section";
  _uid: string;
  [k: string]: unknown;
}
export interface orderMonkeyVideoSection {
  video_thumb?: StoryblokAsset;
  video?: StoryblokAsset;
  title?: StoryblokRichtext;
  component: "ordermonkey_video_section";
  _uid: string;
  [k: string]: unknown;
}
export interface Item {
	text?: string;
	component: "item";
	_uid: string;
	[k: string]: unknown;
}
export interface Card {
	image?: StoryblokAsset;
	title?: string;
	description?: string;
	component: "card";
	_uid: string;
	[k: string]: unknown;
}
export interface Links {
	text?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "links";
	_uid: string;
	[k: string]: unknown;
}

export interface Menu {
	items?: MenuItem[];
	component: "menu";
	_uid: string;
	[k: string]: unknown;
}

export interface MenuItem {
	title?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	SubItems?: SubMenu[];
	component: "menu_item";
	_uid: string;
	[k: string]: unknown;
}

export interface Page {
	body?: (
		| Blog
		| Feature
		| FooterItem
		| Global
		| Grid
		| heroSection
		| Item
		| Links
		| Menu
		| MenuItem
		| Page
		| Robots
		| leftImageSection
		| SubMenu
		| Teaser
	)[];
	robots?: Robots[];
	component: "page";
	_uid: string;
	[k: string]: unknown;
}

export interface Robots {
	index?: boolean;
	follow?: boolean;
	component: "robots";
	_uid: string;
	[k: string]: unknown;
}

export interface leftImageSection {
  image?: StoryblokAsset;
  image_caption?: string;
  title?: string;
  description?: StoryblokRichtext;
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  link_text?: string;
  tags?: Item[];
  component: "left_image_section";
  _uid: string;
  [k: string]: unknown;
}

export interface rightImageSection {
  image?: StoryblokAsset;
  image_caption?: string;
  title?: StoryblokRichtext;
  description?: StoryblokRichtext;
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  link_text?: string;
  tags?: Item[];
  component: "right_image_section";
  _uid: string;
  [k: string]: unknown;
}

export interface smartOrderingSection {
  bg_image?: StoryblokAsset;
  thumbnail?: StoryblokAsset;
  image?: StoryblokAsset;
  title?: StoryblokRichtext;
  description?: StoryblokRichtext;
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  link_text?: string;
  link_2?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  link_text_2?: string;
  component: "smart_ordering_section";
  _uid: string;
  [k: string]: unknown;
}

export interface ordermonkeyEcosystemSection {
  title?: string;
  title_2?: string;
  cards?: Card[];
  component: "ordermonkey_ecosystem_section";
  _uid: string;
  [k: string]: unknown;
}

export interface SubMenu {
	title?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "sub_menu";
	_uid: string;
	[k: string]: unknown;
}

export interface Teaser {
	headline?: string;
	component: "teaser";
	_uid: string;
	[k: string]: unknown;
}
