// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokMultilink, StoryblokAsset, StoryblokMultiasset } from '../storyblok.d.ts';

export type { StoryblokRichtext, StoryblokMultilink, StoryblokAsset, StoryblokMultiasset };
export interface Blog {
  title?: string;
  description?: StoryblokRichtext;
  component: "blog";
  _uid: string;
  [k: string]: unknown;
}

export interface Cards {
  image?: StoryblokAsset;
  title?: string;
  description?: string;
  tag?: string;
  background_image?: StoryblokAsset;
  component: "cards";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterItem {
  items?: Links[];
  component: "footer_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Global {
  burger_menu?: Menu[];
  footer?: FooterItem[];
  header_button?: string;
  logo?: StoryblokMultiasset;
  footer_item_title_1?: string;
  footer_item_title_2?: string;
  footer_item_title_3?: string;
  footer_item_desc_3?: StoryblokRichtext;
  footer_item_title_4?: string;
  footer_item_desc_4?: StoryblokRichtext;
  footer_social_title?: string;
  footer_copyright_text?: string;
  component: "global";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (
    | Blog
    | Cards
    | Feature
    | FooterItem
    | Global
    | Grid
    | HeroSection
    | HeroVideoSection
    | Item
    | LeftImageSection
    | Links
    | Menu
    | MenuItem
    | OrdermonkeyCustomerSection
    | OrdermonkeyDeviceSection
    | OrdermonkeyEcosystemSection
    | OrdermonkeyEcosystemSlide
    | OrdermonkeyFaqSection
    | OrdermonkeyPartnerSection
    | OrdermonkeyVideoSection
    | Page
    | RightImageSection
    | Robots
    | SmartOrderingSection
    | SubMenu
    | Teaser
  )[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  bg_image?: StoryblokAsset;
  title?: string;
  description?: StoryblokRichtext;
  component: "hero_section";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroVideoSection {
  video_thumb?: StoryblokAsset;
  video?: StoryblokAsset;
  title?: StoryblokRichtext;
  description?: StoryblokRichtext;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text?: string;
  component: "hero_video_section";
  _uid: string;
  [k: string]: unknown;
}

export interface Item {
  text?: string;
  component: "item";
  _uid: string;
  [k: string]: unknown;
}

export interface LeftImageSection {
  image?: StoryblokAsset;
  image_caption?: string;
  title?: string;
  description?: StoryblokRichtext;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text?: string;
  tags?: Item[];
  component: "left_image_section";
  _uid: string;
  [k: string]: unknown;
}

export interface Links {
  text?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "links";
  _uid: string;
  [k: string]: unknown;
}

export interface Menu {
  items?: MenuItem[];
  component: "menu";
  _uid: string;
  [k: string]: unknown;
}

export interface MenuItem {
  title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  SubItems?: SubMenu[];
  component: "menu_item";
  _uid: string;
  [k: string]: unknown;
}

export interface OrdermonkeyCustomerSection {
  title?: string;
  cards?: Cards[];
  component: "ordermonkey_customer_section";
  _uid: string;
  [k: string]: unknown;
}

export interface OrdermonkeyDeviceSection {
  title?: string;
  cards?: Cards[];
  component: "ordermonkey_device_section";
  _uid: string;
  [k: string]: unknown;
}

export interface OrdermonkeyEcosystemSection {
  title?: string;
  title_2?: string;
  cards?: Cards[];
  component: "ordermonkey_ecosystem_section";
  _uid: string;
  [k: string]: unknown;
}

export interface OrdermonkeyEcosystemSlide {
  cards?: Cards[];
  component: "ordermonkey_ecosystem_slide";
  _uid: string;
  [k: string]: unknown;
}

export interface OrdermonkeyFaqSection {
  title?: string;
  sub_title?: string;
  cards?: Cards[];
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text?: string;
  component: "ordermonkey_faq_section";
  _uid: string;
  [k: string]: unknown;
}

export interface OrdermonkeyPartnerSection {
  title?: string;
  sub_title?: string;
  cards?: Cards[];
  sub_title_2?: string;
  cards_2?: Cards[];
  component: "ordermonkey_partner_section";
  _uid: string;
  [k: string]: unknown;
}

export interface OrdermonkeyVideoSection {
  video_thumb?: StoryblokAsset;
  video?: StoryblokAsset;
  title?: StoryblokRichtext;
  component: "ordermonkey_video_section";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | Blog
    | Cards
    | Feature
    | FooterItem
    | Global
    | Grid
    | HeroSection
    | HeroVideoSection
    | Item
    | LeftImageSection
    | Links
    | Menu
    | MenuItem
    | OrdermonkeyCustomerSection
    | OrdermonkeyDeviceSection
    | OrdermonkeyEcosystemSection
    | OrdermonkeyEcosystemSlide
    | OrdermonkeyFaqSection
    | OrdermonkeyPartnerSection
    | OrdermonkeyVideoSection
    | Page
    | RightImageSection
    | Robots
    | SmartOrderingSection
    | SubMenu
    | Teaser
  )[];
  robots?: Robots[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface RightImageSection {
  image?: StoryblokAsset;
  image_caption?: string;
  title?: StoryblokRichtext;
  description?: StoryblokRichtext;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text?: string;
  tags?: Item[];
  component: "right_image_section";
  _uid: string;
  [k: string]: unknown;
}

export interface Robots {
  index?: boolean;
  follow?: boolean;
  component: "robots";
  _uid: string;
  [k: string]: unknown;
}

export interface SmartOrderingSection {
  bg_image?: StoryblokAsset;
  thumbnail?: StoryblokAsset;
  image?: StoryblokAsset;
  title?: StoryblokRichtext;
  description?: StoryblokRichtext;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text?: string;
  link_2?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text_2?: string;
  component: "smart_ordering_section";
  _uid: string;
  [k: string]: unknown;
}

export interface SubMenu {
  title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "sub_menu";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Blog | Global | Page;
